name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      my_secret: ${{secrets.commit_secret}}
      
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release

      - run: ls
      - run: |
          cd build/web
          ls
          cd assets
          ls

      - run: |
          cd build/web
          git init
          git config --global user.email onatcipli@outlook.com
          git config --global user.name onatcipli
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/rtviwe/openseadragon.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
